### ISSUE TITLE
SliceCCSharpTask failing to load System.Text.Json 8

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3817]
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB4018	The "SliceCCSharpTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'IceRpc.Slice.Tools.DiagnosticParser' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at IceRpc.Slice.Tools.DiagnosticParser..cctor()
   --- End of inner exception stack trace ---
   at IceRpc.Slice.Tools.DiagnosticParser.Parse(String data)
   at IceRpc.Slice.Tools.SliceCCSharpTask.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance) in C:\Users\jose\source\repos\icerpc-csharp\tools\IceRpc.Slice.Tools\SliceCCSharpTask.cs:line 97
   at Microsoft.Build.Utilities.ToolTask.LogMessagesFromStandardErrorOrOutput(Queue dataQueue, ManualResetEvent dataAvailableSignal, MessageImportance messageImportance, StandardOutputOrErrorQueueType queueType)
   at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	IceRpc.Slice.Tests	C:\Users\jose\source\repos\icerpc-csharp\tools\IceRpc.Slice.Tools\IceRpc.Slice.Tools.targets	51		
```

**Comment by pepone** [comment]
> I don't understand this error. You're not running everything with .NET 8.0?

This happens with Visual Studio 2022, when the SliceC task tries to parse an error that is JSON formatted
