### ISSUE TITLE
Error when running the GenericHost example with Protobuf

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3833]
I am getting:

```
C:\Users\bernard\source\repos\icerpc-csharp\examples\protobuf\GenericHost\Client>dotnet run
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
Failed to connect to the server:
System.NullReferenceException: Object reference not set to an instance of an object.
   at IceRpc.OutgoingRequest..ctor(ServiceAddress serviceAddress) in C:\Users\bernard\source\repos\icerpc-csharp\src\IceRpc\OutgoingRequest.cs:line 57
   at IceRpc.Protobuf.InvokerExtensions.InvokeUnaryAsync[TOutput](IInvoker invoker, ServiceAddress serviceAddress, String operation, IMessage inputMessage, MessageParser`1 messageParser, ProtobufEncodeOptions encodeOptions, IFeatureCollection features, Boolean idempotent, CancellationToken cancellationToken) in C:\Users\bernard\source\repos\icerpc-csharp\src\IceRpc.Protobuf\InvokerExtensions.cs:line 44
   at VisitorCenter.GreeterClient.GreetAsync(GreetRequest message, IFeatureCollection features, CancellationToken cancellationToken) in C:\Users\bernard\source\repos\icerpc-csharp\examples\protobuf\GenericHost\Client\generated\Greeter.IceRpc.cs:line 80
   at GenericHostClient.ClientHostedService.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\bernard\source\repos\icerpc-csharp\examples\protobuf\GenericHost\Client\ClientHostedService.cs:line 36
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bernard\source\repos\icerpc-csharp\examples\protobuf\GenericHost\Client\bin\Any CPU\Debug\net8.0\
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
      Hosting stopping
dbug: Microsoft.Extensions.Hosting.Internal.Host[4]
      Hosting stopped
```

It could be a duplicate of #3832

**Comment by bernardnormier** [comment]
We have the same issue with the client generated by the template icerpc-protobuf-di-client:

```
C:\Users\bernard\source\repos\tmp\MyPDIC>dotnet run
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
Failed to connect to the server:
System.NullReferenceException: Object reference not set to an instance of an object.
   at IceRpc.OutgoingRequest..ctor(ServiceAddress serviceAddress) in C:\Users\bernard\source\repos\icerpc-csharp\src\IceRpc\OutgoingRequest.cs:line 57
   at IceRpc.Protobuf.InvokerExtensions.InvokeUnaryAsync[TOutput](IInvoker invoker, ServiceAddress serviceAddress, String operation, IMessage inputMessage, MessageParser`1 messageParser, ProtobufEncodeOptions encodeOptions, IFeatureCollection features, Boolean idempotent, CancellationToken cancellationToken) in C:\Users\bernard\source\repos\icerpc-csharp\src\IceRpc.Protobuf\InvokerExtensions.cs:line 44
   at MyPDIC.GreeterClient.GreetAsync(GreetRequest message, IFeatureCollection features, CancellationToken cancellationToken) in C:\Users\bernard\source\repos\tmp\MyPDIC\generated\Greeter.IceRpc.cs:line 80
   at MyPDIC.ClientHostedService.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\bernard\source\repos\tmp\MyPDIC\ClientHostedService.cs:line 33
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bernard\source\repos\tmp\MyPDIC\bin\Any CPU\Debug\net8.0\
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
      Hosting stopping
dbug: Microsoft.Extensions.Hosting.Internal.Host[4]
      Hosting stopped
```
