### ISSUE TITLE
Slic idle timeout test failures on Windows

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#4097]
https://github.com/icerpc/icerpc-csharp/actions/runs/11834164792/job/32974300856?pr=4096

```
Failed IceRpc:Tests:Transports:Slic:SlicTransportTests:Connection_with_idle_timeout_and_slow_write_is_not_aborted(False) [2 s]
2024-11-14T09:22:27.4319617Z   Error Message:
2024-11-14T09:22:27.4325179Z    IceRpc.IceRpcException : The connection was lost.
2024-11-14T09:22:27.4328508Z   Stack Trace:
2024-11-14T09:22:27.4340793Z      at IceRpc.Transports.Slic.Internal.SlicConnection.ThrowIfClosed() in /_/src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:line 661
2024-11-14T09:22:27.4386659Z    at IceRpc.Transports.Slic.Internal.SlicStream.ThrowIfConnectionClosed() in /_/src/IceRpc/Transports/Slic/Internal/SlicStream.cs:line 401
2024-11-14T09:22:27.4410589Z    at IceRpc.Transports.Slic.Internal.SlicPipeWriter.WriteAsync(ReadOnlySequence`1 source, Boolean endStream, CancellationToken cancellationToken) in /_/src/IceRpc/Transports/Slic/Internal/SlicPipeWriter.cs:line 101
2024-11-14T09:22:27.4422915Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 618
2024-11-14T09:22:27.4440060Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 628
2024-11-14T09:22:27.4449581Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
2024-11-14T09:22:27.4461066Z    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
2024-11-14T09:22:27.4497061Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
2024-11-14T09:22:27.4511048Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2024-11-14T09:22:27.4515455Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2024-11-14T09:22:27.4524989Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2024-11-14T09:22:27.4546901Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
2024-11-14T09:22:27.4555409Z    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
2024-11-14T09:22:27.4704559Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-14T09:22:27.4706773Z --- End of stack trace from previous location ---
2024-11-14T09:22:27.4708558Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-14T09:22:27.4710775Z    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
2024-11-14T09:22:27.4712528Z    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
2024-11-14T09:22:27.4714149Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
2024-11-14T09:22:27.4715198Z 
2024-11-14T09:22:27.4716359Z   Failed IceRpc:Tests:Transports:Slic:SlicTransportTests:Connection_with_idle_timeout_and_slow_write_is_not_aborted(True) [2 s]
2024-11-14T09:22:27.4717953Z   Error Message:
2024-11-14T09:22:27.4718793Z    IceRpc.IceRpcException : The connection was lost.
2024-11-14T09:22:27.4719734Z   Stack Trace:
2024-11-14T09:22:27.4721383Z      at IceRpc.Transports.Slic.Internal.SlicConnection.ThrowIfClosed() in /_/src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:line 661
2024-11-14T09:22:27.4724329Z    at IceRpc.Transports.Slic.Internal.SlicStream.ThrowIfConnectionClosed() in /_/src/IceRpc/Transports/Slic/Internal/SlicStream.cs:line 401
2024-11-14T09:22:27.4728005Z    at IceRpc.Transports.Slic.Internal.SlicPipeWriter.WriteAsync(ReadOnlySequence`1 source, Boolean endStream, CancellationToken cancellationToken) in /_/src/IceRpc/Transports/Slic/Internal/SlicPipeWriter.cs:line 101
2024-11-14T09:22:27.4732851Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 618
2024-11-14T09:22:27.4737838Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 628
2024-11-14T09:22:27.4741395Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
2024-11-14T09:22:27.4743652Z    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
2024-11-14T09:22:27.4745758Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
2024-11-14T09:22:27.4747350Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2024-11-14T09:22:27.4749137Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2024-11-14T09:22:27.4751706Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2024-11-14T09:22:27.4753627Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
2024-11-14T09:22:27.4755523Z    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
2024-11-14T09:22:27.4757666Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-14T09:22:27.4760617Z --- End of stack trace from previous location ---
2024-11-14T09:22:27.4781959Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-14T09:22:27.4784934Z    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
2024-11-14T09:22:27.4786431Z    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
2024-11-14T09:22:27.4787693Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

**Comment by pepone** [comment]
```
2024-11-14T09:22:27.4410589Z    at IceRpc.Transports.Slic.Internal.SlicPipeWriter.WriteAsync(ReadOnlySequence`1 source, Boolean endStream, CancellationToken cancellationToken) in /_/src/IceRpc/Transports/Slic/Internal/SlicPipeWriter.cs:line 101
2024-11-14T09:22:27.4422915Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 618
2024-11-14T09:22:27.4440060Z    at IceRpc.Tests.Transports.Slic.SlicTransportTests.Connection_with_idle_timeout_and_slow_write_is_not_aborted(Boolean serverIdleTimeout) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\Transports\Slic\SlicTransportTests.cs:line 628
```

https://github.com/icerpc/icerpc-csharp/blob/f89327fe1f7afd1dfa73779b635967b16ca797f6/tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs#L615-L628

The stack is a bit confusing, writing on line 618 `stream.Output.WriteAsync` fails, why does lines 628 appears in the stack at all?  Seems like NUnit does this.

The test took 2s but it was still writing, when it fails, most likely the machine was running slow. I think we should either not run this in parallel or decrease the Delay to 250ms

**Comment by pepone** [comment]
Failed again in https://github.com/icerpc/icerpc-csharp/actions/runs/11834696654/job/32975911192
