### ISSUE TITLE
Listen backlog test failure

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#4099]
This test also failed with a Slow Windows VM, but not clear why this is time sensitive.

https://github.com/icerpc/icerpc-csharp/blob/f89327fe1f7afd1dfa73779b635967b16ca797f6/tests/IceRpc.Tests/Transports/Tcp/TcpTransportTests.cs#L196

This assert seems a bit aleatory, why 25?

```
 IceRpc.Tests test net8.0 failed with 1 error(s) (26.1s)
    C:\Users\jose\source\repos\icerpc-csharp\tests\IceRpc.Tests\Transports\Tcp\TcpTransportTests.cs(196): error TESTERROR:
      IceRpc:Tests:Transports:Tcp:TcpTransportTests:Configure_server_connection_listen_backlog (676ms): Error Message:   Assert.That(connections, Has.Count.LessThanOrEqualTo(25))
        Expected: property Count less than or equal to 25
        But was:  30

      Stack Trace:
         at IceRpc.Tests.Transports.Tcp.TcpTransportTests.Configure_server_connection_listen_backlog() in C:\Users\jose\source\repos\icerpc-csharp\tests\IceRpc.Tests\Transports\Tcp\TcpTransportTests.cs:line 196
         at IceRpc.Tests.Transports.Tcp.TcpTransportTests.Configure_server_connection_listen_backlog() in C:\Users\jose\source\repos\icerpc-csharp\tests\IceRpc.Tests\Transports\Tcp\TcpTransportTests.cs:line 198
         at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
         at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
         at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

      1)    at IceRpc.Tests.Transports.Tcp.TcpTransportTests.Configure_server_connection_listen_backlog() in C:\Users\jose\source\repos\icerpc-csharp\tests\IceRpc.Tests\Transports\Tcp\TcpTransportTests.cs:line 196
```

**Comment by pepone** [comment]
Testing on Windows shows that most of the time connect fails at the 18th connection, but there is also failures with a few more connections 21, 25, and 30 like in the stack above.

Here the whole point of the test is that `TcpListener` call  `Socket.Listen` with the `ListenBacklog` from the TCP options. Accepting a few more connections is just a detail of the Socket implementation which is out of IceRPC control.
