### ISSUE TITLE
Connect_fails_if_listener_is_disposed failure on Ubuntu

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#4103]
See https://github.com/icerpc/icerpc-csharp/actions/runs/11839705688/job/32991791037?pr=4101

```
2024-11-14T14:58:17.3664178Z   Failed IceRpc:Tests:Transports:Tcp:TcpListenerConformanceTests:Connect_fails_if_listener_is_disposed [1 s]
2024-11-14T14:58:17.3675783Z   Error Message:
2024-11-14T14:58:17.3676225Z      Assert.That(caughtException, expression)
2024-11-14T14:58:17.3676808Z   Expected: <IceRpc.IceRpcException>
2024-11-14T14:58:17.3677281Z   But was:  null
2024-11-14T14:58:17.3677517Z 
2024-11-14T14:58:17.3677683Z   Stack Trace:
2024-11-14T14:58:17.3679412Z      at IceRpc.Conformance.Tests.DuplexListenerConformanceTests.Connect_fails_if_listener_is_disposed() in /home/runner/work/icerpc-csharp/icerpc-csharp/tests/IceRpc.Conformance.Tests/Transports/DuplexListenerConformanceTests.cs:line 158
2024-11-14T14:58:17.3682601Z    at IceRpc.Conformance.Tests.DuplexListenerConformanceTests.Connect_fails_if_listener_is_disposed() in /home/runner/work/icerpc-csharp/icerpc-csharp/tests/IceRpc.Conformance.Tests/Transports/DuplexListenerConformanceTests.cs:line 166
2024-11-14T14:58:17.3684736Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
2024-11-14T14:58:17.3686100Z    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
2024-11-14T14:58:17.3687438Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
2024-11-14T14:58:17.3688366Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2024-11-14T14:58:17.3689879Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2024-11-14T14:58:17.3691253Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2024-11-14T14:58:17.3692489Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
2024-11-14T14:58:17.3693653Z    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```

**Comment by pepone** [comment]
Fixed in  #4104
