### ISSUE TITLE
ShutdownRequested_completes_when_inactive_and_inactive_timeout_deferred_by_payload_write(ice,True) failure (Windows)

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#4111]
From https://github.com/icerpc/icerpc-csharp/actions/runs/11843870779/job/33009930133?pr=4101

```
 Failed IceRpc:Tests:ProtocolConnectionTests:ShutdownRequested_completes_when_inactive_and_inactive_timeout_deferred_by_payload_write(ice,True) [2 s]
  Error Message:
     Assert.That(TimeSpan.FromMilliseconds(Environment.TickCount64 - startTime), Is.GreaterThan(TimeSpan.FromMilliseconds(990)).And.LessThan(TimeSpan.FromSeconds(2)))
  Expected: greater than 00:00:00.9900000 and less than 00:00:02
  But was:  00:00:02.1720000

  Stack Trace:
     at IceRpc.Tests.ProtocolConnectionTests.ShutdownRequested_completes_when_inactive_and_inactive_timeout_deferred_by_payload_write(Protocol protocol, Boolean isOneway) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\ProtocolConnectionTests.cs:line 492
   at IceRpc.Tests.ProtocolConnectionTests.ShutdownRequested_completes_when_inactive_and_inactive_timeout_deferred_by_payload_write(Protocol protocol, Boolean isOneway) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\ProtocolConnectionTests.cs:line 492
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

1)    at IceRpc.Tests.ProtocolConnectionTests.ShutdownRequested_completes_when_inactive_and_inactive_timeout_deferred_by_payload_write(Protocol protocol, Boolean isOneway) in D:\a\icerpc-csharp\icerpc-csharp\tests\IceRpc.Tests\ProtocolConnectionTests.cs:line 492
```

**Comment by bernardnormier** [comment]
This test can run in parallel and the 2 seconds is a best guess upper limit. From the logic in the test, the inactivity timeout shouldn't trigger the shutdown requested in less than 1,050 ms (and yet we have 990 ms as lower bound). I propose to increase the upper limit to 3 seconds.
